### ISSUE TITLE
"WebVR Superstar" t-shirt design needed.

### ISSUE THREAD

**Issue by Srushtika** [mozilla/OpenDesign#118]
## Goal: 
A t-shirt design required with the text "WebVR Superstar"
## Info: 
 It will be given to winners of a competition which will be held during May-June in WebVR India community.

## Style Information: 
On the lines of these designs https://mozilla.ninja/gallery/ but with solid colour in order to take care of the cost constraints. May reflect the idea of "Virtual Reality" overall with the new branding guidelines.

## Deadline: 
One week

## Tag: 
Design Needed

**Comment by elioqoshi** [comment]
Hi @Srushtika 
One week is pretty impossible here. Unless someone else wants to do that. I'd advise having at least 3 weeks time for design requests.

**Comment by mukeshpathak345** [comment]
![mozmicky](https://cloud.githubusercontent.com/assets/11034559/25601950/7256c506-2f0d-11e7-805d-5552ab6d29c5.JPG)
![vr_glasses-512 copy copy](https://cloud.githubusercontent.com/assets/11034559/25601948/71fd30d6-2f0d-11e7-82e9-025496ca8493.PNG)
![webvr india t-shirt design](https://cloud.githubusercontent.com/assets/11034559/25601949/7207dcd4-2f0d-11e7-9ff0-b0f2c9e8591d.jpg)
![back design](https://cloud.githubusercontent.com/assets/11034559/25602125/e3168c62-2f0e-11e7-91b0-b0892f48835d.PNG)


Mukesh Pathak T-Shirt Design

**Comment by elioqoshi** [comment]
@mukeshpathak345 Hi there! I think you used some stock graphics here where I'm not sure if that would be allowed unless they are openly licensed :) We should aim for something more personalized I think

**Comment by Tess-welhazi** [comment]
I see there isn't much time left here so here's what i got 
![image](https://cloud.githubusercontent.com/assets/20952652/25775667/b953ae9c-32aa-11e7-9002-4da033577916.png)

![image](https://cloud.githubusercontent.com/assets/20952652/25775683/1bf6e906-32ab-11e7-9f31-aa6413fa3f96.png)

the doge is there due to mozilla's apparent new fascinating with meme culture.

**Comment by elioqoshi** [comment]
@Tess-welhazi Thanks for the suggestions! Doge is usually associated with Servo so I'd not use it here. Also, let's not rush because a 1 week deadline is not realistic. @Srushtika please let us know with a feasible deadline, one week is way too little and seems rather like an afterthought rather than planned. When you organize an event, you don't do it for next week either, right?

**Comment by Tess-welhazi** [comment]
@elioqoshi will succes kid be a better choice?

**Comment by Srushtika** [comment]
Hey @elioqoshi ! The webvr-india community has had a little reorganisation. We wouldn't need this t shirt for now :) I'll re-open the issue when relevant, closing for now !

Thanks !
