### ISSUE TITLE
Poster for Add-on Events

### ISSUE THREAD

**Issue by viswanathamsantosh** [mozilla/OpenDesign#126]
## Goal: 
A poster which we could use for social media publicity.

## Info: 
It will be used for all events around Firefox Add-ons development around the communities.

## Style Information: 
I think you will know about this better. Basically any person who is going to organize an event around Firefox add-ons should be able to hack the poster with the event location, date, time, event name etc. and be able to use it.

## Deadline: 
Sooner the better.

## Tag: 
[Design Needed, Developer Needed]

**Comment by prasannatm** [comment]
![mozilla](https://cloud.githubusercontent.com/assets/13232678/26597119/82bf6848-458e-11e7-9f54-f7520730a1df.png)

**Comment by elioqoshi** [comment]
Can we revisit the style please? It looks more like Google right now :)

**Comment by prasannavijayan** [comment]
![mozilla](https://user-images.githubusercontent.com/3090884/27318226-f7e99c22-55a8-11e7-9eb4-7cebe6cbf943.png)

**Comment by viswanathamsantosh** [comment]
May be we can replace the colors from Mozilla palette to make it sound more of Mozilla?

**Comment by elioqoshi** [comment]
Yeah this is a bit out of line. @prasannavijayan please post the source files so we can revisit

**Comment by barrosgeraldo** [comment]
Hey @viswanathamsantosh, do you still need the poster for social media? If it's the date I see on the poster, it's already expired.

**Comment by viswanathamsantosh** [comment]
Hey @barrosgeraldo , My event is done but we need a generic Event poster which could be hacked and use for all the add-ons events around the globe. Would be glad if you got something. :)

**Comment by barrosgeraldo** [comment]
Hey, thank you for reply. I've recently made banners for Facebook and Twitter to promote Rust and WebVR activities at Brazil, I'll try to take some time this week to create a generic for add-ons, I'll update here when I have it ready for feedback. 

Thank you again, have a nice day.

**Comment by viswanathamsantosh** [comment]
Awesome! Thanks for taking this up geraldo. \o/

**Comment by barrosgeraldo** [comment]
Hi @viswanathamsantosh, thanks for your request.

I've created a banner that you can remix and use to promote your workshops, since they are Add-ons for Firefox, I created using similar arts with the Firefox profile on Facebook.

This banner uses Firefox logo, but you can replace it with your community logo (I recommend), all text is editable, so you can add place name, address and ticket link. You need to have vector software and Fira Sans installed on your computer to remix this one.

Good luck with your workshops and have a nice day. :D

![add-on-events](https://user-images.githubusercontent.com/14970832/28397790-43caab52-6cda-11e7-9c68-0a5b4bfed067.png)

**Comment by barrosgeraldo** [comment]
@elioqoshi, I am not sure if the use of the Add-ons logo are correct, you could check?

**Comment by barrosgeraldo** [comment]
I added a newest banner using Zilla. Closed for now.
