### ISSUE TITLE
Updated Icon for Participation Systems

### ISSUE THREAD

**Issue by mbransn** [mozilla/OpenDesign#128]
## Goal: 
The Mozilla Participation Systems team needs an updated icon that aligns with new Mozilla branding. 

## Info: 
The icon will be used with and without the Participation Systems wordmark (see below). We'll upload it as the avatar for our internal communication channels, utilize it on our presentations and get it made into stickers/shirts/etc to share with our fellow Mozillians!

## Style Information: 
Simple and one color is best (let's start with b/w and go from there color wise). The style should be on brand and reflect the (eventual) updated icons of our products (Mozillians, Discourse, etc). Circles seem to reflect our work most effectively as we are iterative and collaborative. Our work involves other teams and is evolving.

We'd like our icon to communicate and reflect these goals:
- user centered
- multi-disciplinary
- collaborative
- strategic
- integrative
- inclusive

## Deadline: 
Before June All Hands doesn't seem realistic, but if it happened by then @hmitsch would be extremely happy. 

## Tag: 
[Design Needed]

## Wordmark:
![mozilla-parsys-wordmark](https://user-images.githubusercontent.com/18686986/26852540-748ad548-4ac3-11e7-9040-d4de99c412a4.png)

**Comment by elioqoshi** [comment]
Thank you @m-branson ! Here are few alternatives:

![1](https://user-images.githubusercontent.com/5436686/27005273-4dbd255a-4e1b-11e7-9273-197ce9db3a20.jpg)


I didn't change the icon as it has been widely used before as well.

What do you think?

**Comment by hmitsch** [comment]
@elioqoshi thank you very much. I really like it.
@m-branson should we print the purple one on a white background on round stickers?

@a-kilroy FYI

**Comment by m-branson** [comment]
Thanks @elioqoshi, this looks like a good evolution of the current ParSys icon/wordmark. Appreciate you taking the time to work on it. 👍 Can you send through your source file so that I can prep sticker files for @hmitsch today or tomorrow?

@hmitsch once I have Elio's file I'll make a sticker version for you & the team to approve. I think this is a great solution for June All Hands, though I would like to explore the icon further in the next part of the year. Perhaps we do a small printing of stickers for this set? I think you mentioned 50 on Friday?

cc/ @a-kilroy

**Comment by hmitsch** [comment]
Files are stored here: https://drive.google.com/drive/folders/0B0vmiicLLrGuVjlCMGt4WHdCcG8

**Comment by elioqoshi** [comment]
I'd keep this open as the current logo is only a temporary solution and we should update it within our guidelines fully as soon as we know how to proceed

**Comment by elioqoshi** [comment]
Closing this as I don't think the guidelines will provide better guidance for these cases.
