### ISSUE TITLE
Create a design for hexbin stickers (Firefox and Nightly)

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/OpenDesign#152]
## Goal: 
We would like to have a design for hexbin hexagonal stickers (https://github.com/maxogden/hexbin) to be able to print them for a conference before the beginning of October. It would be great if the designs are for both release Firefox and Nightly, maybe even with the new logos.

## Info: 
The stickers should be usable as a regular Firefox stickers on laptop lid. From our experience, a lot of people are asking for a smaller sticker for some time, as the lid surface is precious. I hope Reps swag could also include these in the future, but that won't be my decision.

## Style Information: 
- https://github.com/maxogden/hexbin
- http://hexb.in/

## Deadline: 
Sooner is better, for the October conference we would probably need the design ready before the half of September.

## Tag: 
Design Needed

**Comment by barrosgeraldo** [comment]
Hi @MikkCZ, thank you for your request! These cool stickers are very small, but maybe I'm wrong because I like big and crazy things hahaha, they're ready and [available for download in our repository](https://github.com/mozilla/OpenDesign/tree/master/2017/Swag%26Printouts/hexbin_stickers).
![prancheta 1firefox](https://user-images.githubusercontent.com/14970832/29489191-819f7d70-84f1-11e7-80ba-88b83a9bdcf5.png)

We do not have the newest logo that is apparently under development or review, but we have the current Firefox and Nightly logo.

Anyway, I think it's cool to also create one for Firefox Focus, but we'd need to get the vector file, if you need one for Focus, open a new request and we'll try to get the vector logo. Cheers!

**Comment by MikkCZ** [comment]
Wow, cool. @barrosgeraldo can you also add these to the haxbin GitHub repo, so everyone looking there can find it?

**Comment by elioqoshi** [comment]
@barrosgeraldo let me know if you can push them also to the haxbin repo :)

**Comment by barrosgeraldo** [comment]
Hi @elioqoshi , yes, I can, however it is interesting that tasks outside the repository are made by those who requested, it is not always just to push a file, but to open issue and generate other complementary files, are tasks that go beyond ours here.

**Comment by barrosgeraldo** [comment]
https://github.com/maxogden/hexbin/pull/161

**Comment by elioqoshi** [comment]
@barrosgeraldo True. But the lines are blurry anyway. We did it because we think it would be good to do, not because someone requested it here, right?

**Comment by barrosgeraldo** [comment]
Yep.
