### ISSUE TITLE
Tech Speakers logo potential update & style discussion

### ISSUE THREAD

**Issue by elioqoshi** [mozilla/OpenDesign#42]
Our current Tech Speakers logo has a wide orange gradient spectrum, limiting the choice of background colors to use with it. We have found ourselves use the blue heart as a background to avoid this. To give this a small update, I tweaked the colors of the gradient-like shapes to more saturated and darker colors, in order for it to look good also on white backgrounds. The third logo is the original Tech Speakers icon.

![ts1](https://cloud.githubusercontent.com/assets/5436686/13722361/1843f8fc-e843-11e5-9768-e3e3be6559d6.jpg)
![ts2](https://cloud.githubusercontent.com/assets/5436686/13722362/186efaac-e843-11e5-94eb-7c75c5249b9a.jpg)

I personally prefer the 2nd version of the gradient.

![ts3](https://cloud.githubusercontent.com/assets/5436686/13722359/138cb4c0-e843-11e5-8ed6-d57b533aa848.jpg)

This also looks great on monochrome environments incase we ever need it

What do you think? Would this make sense to update? It would for me, but I believe we need to facilitate a discussion around this for obvious reasons :)

**Comment by havi** [comment]
@elioqoshi Thanks for doing this work - I agree w/you on #2 - I think it reads best on a white background. I strongly prefer to keep the blue background for as many use cases as possible - I think the blue really makes it all sing...  Question: Is the lettering you're using a Moz standard shade of charcoal gray? HTH...

**Comment by viswanathamsantosh** [comment]
Hey elio, Amazing work as always. I like the 2nd logo on blue background. Even the black and white logo looks good.may be we can use it when needed. :)

**Comment by anefzaoui** [comment]
Hey Elio,
Text on white is indeed good looking. I like it and I feel like it rhymes with the visual identity of other text-based Mozilla brands. But I feel like the Orange-white-ish grandient doesn't look good on white, maybe a little bit of contour aka borders would help?

I still like the text on blue background the most tho, I feel like the blue is what gives "TechSpeakers" as an identity its uniqueness. And to be more specific the version with logo's gradient going from Orange to gray/white. i.e.:
![techspeakers hoodie](https://cloud.githubusercontent.com/assets/1832078/13770157/5f76f348-ea85-11e5-8f98-f87eaa72d8c9.jpg)

Otherwise, can we also have a transparent-background version? For that probably replace the lack of blue background by using that blue as a border for the logo and text? I'm curious how would that LOOK :D

And finally, for the final result: SVGs are a great plus if you ask me! :)

**Comment by elioqoshi** [comment]
Thanks guys!

@havi Yep, standard MozGray

@anefzaoui borders wouldn't help really. White background should be a rare usecase (I hope not more than 10%) so we should try to keep it consistent. It's like the Facebook logo. You usually see it white on blue, but they also have a version blue on white for specific cases. Blue stroke looks really bad on white also :/

SVG also of course, it's more like the medium, rather than a feature :D

**Comment by Junaed33** [comment]
Hi Elioqoshi,
The second version of the gradient is much better than other two. It's actually much user friendly, easily visible and it's better to look.

**Comment by elioqoshi** [comment]
@Junaed33 I like that one as well! I will try to wrap the new identity up before the work week.

**Comment by barrosgeraldo** [comment]
@elioqoshi, has this project already updated the logo? Already have a time that the guidelines have been released maybe the changes have already been made from team side.

**Comment by abibb** [comment]
@barrosgeraldo Hey there , so i think the project and logo is completed already and you can check this link out too, https://wiki.mozilla.org/TechSpeakers, the logo is changed a bit.

**Comment by elioqoshi** [comment]
Not really. That's the very first logo @abibb 
I dropped the ball on this one but will coordinate with @mozmike and @havi

**Comment by kindavishal** [comment]
The "mozilla" font has changed now, should this get an update as well?

**Comment by kindavishal** [comment]
The logo has been updated by the staff internally (probably) I came to know about it from a [Techspeaker on Twitter](https://twitter.com/imJenal/status/1162611637041291270?s=19)
Closing this issue! :sparkles:
