### ISSUE TITLE
Typography of Mozilla L10n Wordmark

### ISSUE THREAD

**Issue by Ryuno-Ki** [mozilla/OpenDesign#77]
Not a request, but an issue/a question ;-)

Today, @elioqoshi shared some drafts of … name tags for Mozilla L10N Slovenia. Its header looked like this:
![mozl10n](https://cloud.githubusercontent.com/assets/3097194/16505005/272b5372-3f1b-11e6-8052-b853e691ee8f.png)

![mozl10ntypography](https://cloud.githubusercontent.com/assets/3097194/16504899/8c9c5eaa-3f1a-11e6-9c71-593995d9c60f.png)

As you can see I inserted a black bar in it. (Sorry for the low quality here - managed to copy it from Telegram Desktop somehow and loaded it in GIMP).

To me, the pipe between Mozilla and l10n looks displaced. I assume it is because the upper end of the pipe starts on the lower left corner of the upper end of the ls of Mozilla.

My question: Is that on purpose? Anyone else feeling it misplaced?

I want to understand the reasoning behind it. Elio said it was from official Mozilla creative team and I should ask @mart3ll here.

**Comment by wbranton** [comment]
I agree that it does look odd. Part of the reason that it looks so odd is probably because the Mozilla logo and l10n are not vertically aligned properly. It looks like the line in the middle has been vertically aligned with the "a" in Mozilla. The alignment would look strange if you centered it to the entire Mozilla logo though because the logo isn't vertically balanced. I'm not sure what you could do to make it look perfect, but as it is right now, it's not good.

**Comment by elioqoshi** [comment]
The name of the project will always be smaller than the Mozilla wordmark. Maybe I did a mistake here and it's my fault so let me check if that's the case.
